export const PLAN_CREATE_REQUEST = 'PLAN_CREATE_REQUEST'
export const PLAN_CREATE_SUCCESS = 'PLAN_CREATE_SUCCESS'
export const PLAN_CREATE_FAIL = 'PLAN_CREATE_FAIL'
export const PLAN_CREATE_RESET = 'PLAN_CREATE_RESET'

export const PLAN_LIST_REQUEST = 'PLAN_LIST_REQUEST'
export const PLAN_LIST_SUCCESS = 'PLAN_LIST_SUCCESS'
export const PLAN_LIST_FAIL = 'PLAN_LIST_FAIL'
