export const WALLET_CREATE_REQUEST = 'WALLET_CREATE_REQUEST'
export const WALLET_CREATE_SUCCESS = 'WALLET_CREATE_SUCCESS'
export const WALLET_CREATE_FAIL = 'WALLET_CREATE_FAIL'
export const WALLET_CREATE_RESET = 'WALLET_CREATE_RESET'

export const WALLET_DETAILS_MY_REQUEST = 'WALLET_DETAILS_MY_REQUEST'
export const WALLET_DETAILS_MY_SUCCESS = 'WALLET_DETAILS_MY_SUCCESS'
export const WALLET_DETAILS_MY_FAIL = 'WALLET_DETAILS_MY_FAIL'

export const WALLET_LIST_MY_REQUEST = 'WALLET_LIST_MY_REQUEST'
export const WALLET_LIST_MY_SUCCESS = 'WALLET_LIST_MY_SUCCESS'
export const WALLET_LIST_MY_FAIL = 'WALLET_LIST_MY_FAIL'
export const WALLET_LIST_MY_RESET = 'WALLET_LIST_MY_RESET'

export const WALLET_UPDATE_REQUEST = 'WALLET_UPDATE_REQUEST'
export const WALLET_UPDATE_SUCCESS = 'WALLET_UPDATE_SUCCESS'
export const WALLET_UPDATE_FAIL = 'WALLET_UPDATE_FAIL'
export const WALLET_UPDATE_RESET = 'WALLET_UPDATE_RESET'

export const WALLET_DELETE_REQUEST = 'WALLET_DELETE_REQUEST'
export const WALLET_DELETE_SUCCESS = 'WALLET_DELETE_SUCCESS'
export const WALLET_DELETE_FAIL = 'WALLET_DELETE_FAIL'
export const WALLET_DELETE_RESET = 'WALLET_DELETE_RESET'

export const WALLET_SET_CURRENT = 'WALLET_SET_CURRENT'
export const WALLET_CLEAR_CURRENT = 'WALLET_CLEAR_CURRENT'

export const WALLET_SELECT_SET_CURRENT = 'WALLET_SELECT_SET_CURRENT'
export const WALLET_SELECT_CLEAR_CURRENT = 'WALLET_SELECT_CLEAR_CURRENT'

export const WALLET_GET_TRANSACTIONS_REQUEST = 'WALLET_GET_TRANSACTIONS_REQUEST'
export const WALLET_GET_TRANSACTIONS_SUCCESS = 'WALLET_GET_TRANSACTIONS_SUCCESS'
export const WALLET_GET_TRANSACTIONS_FAIL = 'WALLET_GET_TRANSACTIONS_FAIL'
export const WALLET_GET_TRANSACTIONS_RESET = 'WALLET_GET_TRANSACTIONS_RESET'

export const WALLET_GET_TRANSACTION_REQUEST = 'WALLET_GET_TRANSACTION_REQUEST'
export const WALLET_GET_TRANSACTION_SUCCESS = 'WALLET_GET_TRANSACTION_SUCCESS'
export const WALLET_GET_TRANSACTION_FAIL = 'WALLET_GET_TRANSACTION_FAIL'
export const WALLET_GET_TRANSACTION_RESET = 'WALLET_GET_TRANSACTION_RESET'

export const TRANSACTION_SET_CURRENT = 'TRANSACTION_SET_CURRENT'
export const TRANSACTION_CLEAR_CURRENT = 'TRANSACTION_CLEAR_CURRENT'

export const WALLET_CREATE_TRANSACTION_REQUEST =
  'WALLET_CREATE_TRANSACTION_REQUEST'
export const WALLET_CREATE_TRANSACTION_SUCCESS =
  'WALLET_CREATE_TRANSACTION_SUCCESS'
export const WALLET_CREATE_TRANSACTION_FAIL = 'WALLET_CREATE_TRANSACTION_FAIL'
export const WALLET_CREATE_TRANSACTION_RESET = 'WALLET_CREATE_TRANSACTION_RESET'

export const WALLET_UPDATE_TRANSACTION_REQUEST =
  'WALLET_UPDATE_TRANSACTION_REQUEST'
export const WALLET_UPDATE_TRANSACTION_SUCCESS =
  'WALLET_UPDATE_TRANSACTION_SUCCESS'
export const WALLET_UPDATE_TRANSACTION_FAIL = 'WALLET_UPDATE_TRANSACTION_FAIL'
export const WALLET_UPDATE_TRANSACTION_RESET = 'WALLET_UPDATE_TRANSACTION_RESET'

export const WALLET_DELETE_TRANSACTION_REQUEST =
  'WALLET_DELETE_TRANSACTION_REQUEST'
export const WALLET_DELETE_TRANSACTION_SUCCESS =
  'WALLET_DELETE_TRANSACTION_SUCCESS'
export const WALLET_DELETE_TRANSACTION_FAIL = 'WALLET_DELETE_TRANSACTION_FAIL'
export const WALLET_DELETE_TRANSACTION_RESET = 'WALLET_DELETE_TRANSACTION_RESET'
